### ISSUE TITLE
change example onscreen text

### ISSUE THREAD

**Issue by ofZach** [roymacdonald/ofxHiResRenderer#1]
great addon! 

just a note that the example text has "Press the space key to render what you are currently seeing" but the code expects return key....

**Comment by roymacdonald** [comment]
Hey Zach!
Thanks. I have just updated it. I saw that you had some nice prints for your sketches. did you use this addon for that?
cheers

**Comment by ofZach** [comment]
hey thanks -- for those I used a large FBO but I am working on some more high res outputs for prints and client work at the moment.....  I am working now on modifying this addon to pass on more information to do 2d graphics (such as shaders) at higher res (I think drawScene needs to know some info like the rectangle it is in the image)....  will let you know how it goes!

**Comment by roymacdonald** [comment]
I see. Sure! Just make a PR and I'll merge. I haven't used this addon for a while so any improvement is very welcome.
take care.
